package com.fivepapa.backend.common.controller;

import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * CsrfController
 * Provides CSRF token endpoint for frontend applications
 *
 * The CSRF token is automatically generated by Spring Security and stored in a cookie.
 * This endpoint allows the frontend to retrieve the token value to include in subsequent requests.
 */
@RestController
@RequestMapping("/api")
public class CsrfController {

    /**
     * Get CSRF token
     * GET /api/csrf
     *
     * Spring Security automatically generates a CSRF token and stores it in a cookie named "XSRF-TOKEN".
     * The frontend should read this cookie and include the token value in the "X-XSRF-TOKEN" header
     * for all state-changing requests (POST, PUT, DELETE, PATCH).
     *
     * @param csrfToken automatically injected by Spring Security
     * @return CSRF token details
     */
    @GetMapping("/csrf")
    public CsrfToken getCsrfToken(CsrfToken csrfToken) {
        return csrfToken;
    }
}
